# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39f953e92c8e646617a9ae9dee5ef3c8fce5499e5d9d967ca5cb236664307324fbf68be9de7173c9e6b262b3099ae64786747eea17ddd38fc96f0315a40a257a

test:
  secret_key_base: 13caedd4c723499ebb374a829645192717c56c78dd4a895702e8a15d8d97c87e71f62b0c8dc65da3b01c16b6866d5295bc89cbb6762a65acf05e89eb755b9291

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
